#!/bin/sh
/bin/mount -t proc none /proc
/bin/mount -t sysfs sysfs /sys
/bin/mount -t ramfs /tmp
/bin/mount -t ramfs /mnt
#/bin/mkdir /mnt/pts
/bin/mkdir  /dev/pts
/bin/mount -t devpts none /dev/pts


telnetd &
sleep 2

cd /tmp

insmod /usb/gnand.ko
insmod /usb/nanddrv.ko
sleep 1
insmod /usb/g_mass_storage.ko file=/dev/sda1 stall=0 removable=1
sleep 1
insmod /usb/gpio.ko
mknod /dev/GPIO c 126 0

/bin/mount -t jffs2 /dev/mtdblock0 /var
#/bin/mount -t vfat /dev/sda /mnt

telnetd &

ifconfig lo up

/bin/mount -t vfat /dev/sda1 /mnt
sleep 3

cd /tmp
cp -rf /mnt/*.xml /tmp
cp -rf /usb/while ./
cp -rf /usb/macaddr ./
cp -rf /usb/change_path ./
#cp `cat /var/data/boot.info` ./
#cp /var/server_gz ./
#sleep 1
#tar zxvf server*
#rm server*
#tar zxvf server_gz
#rm server_gz
./while &
sleep 2
echo "DONE"
